build:
	dotnet build
clean:
	dotnet clean
restore:
	dotnet restore
watch:
	dotnet watch --project src/GradeBook/GradeBook.csproj run
start:
	dotnet run --project src/GradeBook/GradeBook.csproj
# dotnet run --project test/GradeBook.Tests/GradeBook.Tests.csproj